---
# Concourse pipeline for backrest-operator (no inject-slack-notifications).

resources:
  - name: ci-shared
    type: git
    icon: github
    source:
      uri: https://github.com/Reactive-Network/ci.git
      branch: master
      paths:
        - concourse/
      username: ((github-access-token.username))
      password: ((github-access-token.password))
    check_every: 1m

  - name: ci-config
    type: git
    icon: github
    source:
      uri: https://github.com/Reactive-Network/infra.git
      branch: main
      paths:
        - concourse/
      username: ((github-access-token.username))
      password: ((github-access-token.password))
    check_every: 1m

  - name: app-git
    type: git
    icon: github
    source:
      uri: https://github.com/Danpiel/backrest-operator.git
      branch: master
      username: ((github-access-token.username))
      password: ((github-access-token.password))
    webhook_token: ((webhook-token-backrest-operator))
    check_every: 1m

  - name: app-git-tags
    type: git
    icon: github
    source:
      uri: https://github.com/Danpiel/backrest-operator.git
      tag_filter: "v*"
      username: ((github-access-token.username))
      password: ((github-access-token.password))
    webhook_token: ((webhook-token-backrest-operator-tags))
    check_every: 1m

  - name: builder-image
    type: registry-image
    source:
      repository: ghcr.io/reactive-network/ci-image
      tag: builder-1d296957
      username: ((ghcr-credentials.username))
      password: ((ghcr-credentials.password))

  - name: deployer-image
    type: registry-image
    source:
      repository: ghcr.io/reactive-network/ci-image
      tag: deployer-14da7d57
      username: ((ghcr-credentials.username))
      password: ((ghcr-credentials.password))

groups:
  - name: meta
    jobs:
      - set-self
  - name: ci
    jobs:
      - unit-test
      - helm-lint
      - build-images
  - name: release-flow
    jobs:
      - release

jobs:
  - name: set-self
    plan:
      - in_parallel:
          - get: app-git
            trigger: true
          - get: ci-shared
          - get: ci-config
      - set_pipeline: self
        file: app-git/concourse/pipelines/backrest-operator.yml
    on_failure:
      try:
        task: slack-notify
        file: ci-shared/concourse/tasks/slack-notify.yml
        params:
          SLACK_TOKEN: ((slack-ci.token))
          SLACK_CHANNEL: ((slack-ci.channel))
          ALERT_TYPE: failed
          PIPELINE_NAME: backrest-operator
          JOB_NAME: set-self

  - name: unit-test
    plan:
      - in_parallel:
          steps:
            - get: app-git
              trigger: true
            - get: ci-config
              passed: [set-self]
            - get: ci-shared
              passed: [set-self]
            - get: builder-image
      - try:
          task: slack-notify
          file: ci-shared/concourse/tasks/slack-notify.yml
          params:
            SLACK_TOKEN: ((slack-ci.token))
            SLACK_CHANNEL: ((slack-ci.channel))
            ALERT_TYPE: started
            PIPELINE_NAME: backrest-operator
            JOB_NAME: unit-test
      - do:
          - task: unit-test
            image: builder-image
            file: app-git/concourse/tasks/unit-test.yml
            input_mapping:
              app-git: app-git
              ci-config: ci-config
        on_success:
          try:
            task: slack-notify
            file: ci-shared/concourse/tasks/slack-notify.yml
            params:
              SLACK_TOKEN: ((slack-ci.token))
              SLACK_CHANNEL: ((slack-ci.channel))
              ALERT_TYPE: success
              PIPELINE_NAME: backrest-operator
              JOB_NAME: unit-test
        on_failure:
          try:
            task: slack-notify
            file: ci-shared/concourse/tasks/slack-notify.yml
            params:
              SLACK_TOKEN: ((slack-ci.token))
              SLACK_CHANNEL: ((slack-ci.channel))
              ALERT_TYPE: failed
              PIPELINE_NAME: backrest-operator
              JOB_NAME: unit-test

  - name: helm-lint
    plan:
      - in_parallel:
          steps:
            - get: app-git
              trigger: true
            - get: ci-config
              passed: [set-self]
            - get: ci-shared
              passed: [set-self]
            - get: deployer-image
      - try:
          task: slack-notify
          file: ci-shared/concourse/tasks/slack-notify.yml
          params:
            SLACK_TOKEN: ((slack-ci.token))
            SLACK_CHANNEL: ((slack-ci.channel))
            ALERT_TYPE: started
            PIPELINE_NAME: backrest-operator
            JOB_NAME: helm-lint
      - do:
          - task: helm-lint
            image: deployer-image
            file: app-git/concourse/tasks/helm-lint.yml
            input_mapping:
              app-git: app-git
        on_success:
          try:
            task: slack-notify
            file: ci-shared/concourse/tasks/slack-notify.yml
            params:
              SLACK_TOKEN: ((slack-ci.token))
              SLACK_CHANNEL: ((slack-ci.channel))
              ALERT_TYPE: success
              PIPELINE_NAME: backrest-operator
              JOB_NAME: helm-lint
        on_failure:
          try:
            task: slack-notify
            file: ci-shared/concourse/tasks/slack-notify.yml
            params:
              SLACK_TOKEN: ((slack-ci.token))
              SLACK_CHANNEL: ((slack-ci.channel))
              ALERT_TYPE: failed
              PIPELINE_NAME: backrest-operator
              JOB_NAME: helm-lint

  - name: build-images
    plan:
      - in_parallel:
          steps:
            - get: app-git
              passed: [unit-test, helm-lint]
              trigger: true
            - get: ci-config
              passed: [set-self]
            - get: ci-shared
              passed: [set-self]
            - get: builder-image
      - try:
          task: slack-notify
          file: ci-shared/concourse/tasks/slack-notify.yml
          params:
            SLACK_TOKEN: ((slack-ci.token))
            SLACK_CHANNEL: ((slack-ci.channel))
            ALERT_TYPE: started
            PIPELINE_NAME: backrest-operator
            JOB_NAME: build-images
      - do:
          - task: build-images
            image: builder-image
            file: app-git/concourse/tasks/build-images.yml
            input_mapping:
              app-git: app-git
              ci-config: ci-config
            params:
              GHCR_USERNAME: ((ghcr-credentials.username))
              GHCR_PASSWORD: ((ghcr-credentials.password))
        on_success:
          try:
            task: slack-notify
            file: ci-shared/concourse/tasks/slack-notify.yml
            params:
              SLACK_TOKEN: ((slack-ci.token))
              SLACK_CHANNEL: ((slack-ci.channel))
              ALERT_TYPE: success
              PIPELINE_NAME: backrest-operator
              JOB_NAME: build-images
        on_failure:
          try:
            task: slack-notify
            file: ci-shared/concourse/tasks/slack-notify.yml
            params:
              SLACK_TOKEN: ((slack-ci.token))
              SLACK_CHANNEL: ((slack-ci.channel))
              ALERT_TYPE: failed
              PIPELINE_NAME: backrest-operator
              JOB_NAME: build-images

  - name: release
    plan:
      - in_parallel:
          steps:
            - get: app-git-tags
              trigger: true
            - get: ci-config
              passed: [set-self]
            - get: ci-shared
              passed: [set-self]
            - get: builder-image
      - try:
          task: slack-notify
          file: ci-shared/concourse/tasks/slack-notify.yml
          params:
            SLACK_TOKEN: ((slack-ci.token))
            SLACK_CHANNEL: ((slack-ci.channel))
            ALERT_TYPE: started
            PIPELINE_NAME: backrest-operator
            JOB_NAME: release
      - do:
          - task: release
            image: builder-image
            file: app-git/concourse/tasks/release.yml
            input_mapping:
              app-git: app-git-tags
              ci-config: ci-config
            params:
              GHCR_USERNAME: ((ghcr-credentials.username))
              GHCR_PASSWORD: ((ghcr-credentials.password))
              GITHUB_TOKEN: ((github-access-token.password))
        on_success:
          try:
            task: slack-notify
            file: ci-shared/concourse/tasks/slack-notify.yml
            params:
              SLACK_TOKEN: ((slack-ci.token))
              SLACK_CHANNEL: ((slack-ci.channel))
              ALERT_TYPE: success
              PIPELINE_NAME: backrest-operator
              JOB_NAME: release
        on_failure:
          try:
            task: slack-notify
            file: ci-shared/concourse/tasks/slack-notify.yml
            params:
              SLACK_TOKEN: ((slack-ci.token))
              SLACK_CHANNEL: ((slack-ci.channel))
              ALERT_TYPE: failed
              PIPELINE_NAME: backrest-operator
              JOB_NAME: release
