---
platform: linux

inputs:
  - name: app-git
  - name: ci-shared

params:
  GHCR_USERNAME: ""
  GHCR_PASSWORD: ""
  GHCR_OWNER: ""
  CI_SHARED_DIR: ../ci-shared

run:
  path: bash
  args:
    - concourse/scripts/build-images.sh
  dir: app-git
