---
platform: linux

inputs:
  - name: app-git
  - name: ci-config

params:
  GHCR_USERNAME: ""
  GHCR_PASSWORD: ""
  GITHUB_TOKEN: ""
  CI_CONFIG_DIR: ../ci-config

run:
  path: bash
  args:
    - concourse/scripts/release.sh
  dir: app-git
