---
platform: linux

inputs:
  - name: app-git

caches:
  - path: cache/gomod
  - path: cache/gocache
  - path: cache/gobin

run:
  path: bash
  args:
    - concourse/scripts/unit-test.sh
  dir: app-git
